### ISSUE TITLE
Sudoku Speicher-Logik

### ISSUE THREAD

**Issue by rrancerr** [waghD/pr_service_engineering#17]

**Comment by rrancerr** [comment]
Im Zuge von #13 mit @vambi festgestellt:
Die aktuelle REST API könnte dahingehend optimiert werden, dass man keine Feld-ID's für das updaten der einzelnen Felder gebraucht werden.

Sonst ist es so, dass wenn ein gesamtes Sudoko-Grid updaten möchte, muss man zunächst sich die bereits existierenden Felder raussuchen, dann deren ID abfragen und m t dem x/y wert abgleichen, sodass diese separat geupdatet werden können. Alle nicht existierenden Felder werden dann als neue Felder registriert, dass macht es unnötig komplex.

Optimal wäre es, lediglich die Sudoku-ID und den x, y Wert zu übergeben, da dieser jedes Feld so eindeutig bereits identifiziert. Das macht die Feld ID aus einer Frontend-sicht obsolet.

Wenn man dann ein gesamtes Grid updaten möchte übergibt man dann lediglich ein Array mit den Feldern wie beim neu anlegen und updatet die Felder dann so.

**Comment by vambi** [comment]
- [ ] Change Primary Key to a Composite of X and Y
- [ ] Make fields updateable in Bulk
- [ ] Change DTO so that we do not need Entities in Frontend

**Comment by rrancerr** [comment]
Wie besprochen benötigen wir auch noch zusätzlich eine Flag für jedes Feld, ob es editierbar sein soll oder nicht, um die Felder auch nach dem Speichern wieder unterscheiden zu können.

**Comment by rrancerr** [comment]
Wir benötigen auch noch ein Feld, dass die aktuelle "Bearbeitungszeitzeit" bereitstellt, sodass man anch dem speichern wieder bei der Zeit weitermachen kann, bei der man aufgehört hat
