### ISSUE TITLE
Swagger Doku ergänzen/ausformulieren

### ISSUE THREAD

**Issue by rrancerr** [waghD/pr_service_engineering#30]
Die automatisch generierte Swagger doku sollte noch um zusätzliche "eigenhändige" Beschreibungen ergänzt werden, sodass die einzelnen API-Calls besser verständlich sind.

Zusätzlich dazu sind noch in der generierten Doku einige Pflicht-Parameter falsch, z.B. bei GET /api/sudokus. **muss** man laut swagger zwingend die params für die pagination mitgeben, was aber nicht der realität entspricht

**Comment by waghD** [comment]
Stimmt, des mit die Pflichtfelder is glaub ich weils in der Backend funktion eigentlich auch als Pflichtfelder deklariert sind und dann ned enforced wird.
Sollt ma dort dann einfach als optional definieren, dann ists in der Swagger doku vermutlich auch optional
