### ISSUE TITLE
Datenbank Schema anpassen

### ISSUE THREAD

**Issue by waghD** [waghD/pr_service_engineering#41]
Wir brauchen noch ein paar zusätzliche Properties beim Sudoku

- [ ] Variante
- [ ] User dem das Sudoku gehört
- [ ] ...

Und vermutlich noch ein eigenes Datenbankschema für die Userdatenbank

**Comment by rrancerr** [comment]
In diesem Zug müsste man dann auch noch die API Endpunkte anpassen/hinzufügen.
D.h. 

- [ ] beim updaten von feldern/sudokus dann noch eine (optionale?) User-ID mitgeben um das sudoku einem User zuzuordnen und dann abspeichern
- [ ] beim abfragen von sudokus eine User-ID mitgeben, sodass man gespeicherte Sudokus user-bezogen bekommt
