### ISSUE TITLE
Optional: Webauthn checken

### ISSUE THREAD

**Issue by rrancerr** [waghD/pr_service_engineering#59]
Die Idee ist ob es möglich ist Webauthn (https://webauthn.io/) zu unseremd Sudoku hinzuzufügen. Es muss gechcekt werden ob das technisch möglich ist.

Das ist kein zwingend erforderliches Featue für Release 3.

Maximaler Zeitaufwand: 5h
Danach ggf. Abbruch und invalidieren

**Comment by waghD** [comment]
Gibt für WebAuthn noch keine libraries die wir verwenden könnten, und wird bisher auch von keinem Identity Provider supported. 

Wär definitiv zu viel für des Projekt WebAuthn von 0 zu implementieren
