### ISSUE TITLE
Logout Funktionalität implementieren

### ISSUE THREAD

**Issue by rrancerr** [waghD/pr_service_engineering#76]
API schnittstelle erstellen, die einen Logout durchführt.

benötigt für Anmeldebanner Funktionalität

**Comment by rrancerr** [comment]
@vambi @waghD machts euch bitte aus wer das für RC 3 noch macht

**Comment by waghD** [comment]
@rrancerr ma braucht ka api fürn logout. Des is a frontend operation. Im backend wird ned gespeichert wer gerade online ist
